"use client";

import { useEffect, useRef, useState } from "react";
import type { BlockEntity } from "@/builder/types/entity";
import { useBuilderDispatch } from "@/hooks/builder/use-builder-store.hook";
import { renderTexToHtml } from "@/services/third-party-facade/katex";

type Props = {
  block: BlockEntity;
};

/**
 * MathBlock — renders a `math-block` kind block.
 *
 * Two states:
 *  - editing: monospace contentEditable textarea-like div.
 *  - preview: KaTeX HTML rendered via dangerouslySetInnerHTML.
 *
 * Transition rules:
 *  - Mount with empty tex → editing mode immediately.
 *  - Mount with existing tex → preview mode.
 *  - Click / Enter/Space in preview → editing mode.
 *  - Blur or Shift+Enter or Escape in editing mode → commit tex → preview mode.
 */
export function MathBlock({ block }: Props) {
  const tex = (block.data.tex as string | undefined) ?? "";
  const [editing, setEditing] = useState(tex.length === 0);
  const editorRef = useRef<HTMLDivElement | null>(null);
  const dispatch = useBuilderDispatch();

  // Focus the editor when entering editing mode.
  useEffect(() => {
    if (!editing) return;
    const el = editorRef.current;
    if (!el) return;
    el.focus();
    // Place caret at end.
    const sel = window.getSelection();
    if (sel) {
      const range = document.createRange();
      range.selectNodeContents(el);
      range.collapse(false);
      sel.removeAllRanges();
      sel.addRange(range);
    }
  }, [editing]);

  const commitAndPreview = () => {
    const el = editorRef.current;
    const newTex = el ? el.innerText.trim() : tex;
    dispatch({
      type: "UPDATE_BLOCK",
      nodeId: block.id,
      patch: { data: { ...block.data, tex: newTex } },
    });
    setEditing(false);
  };

  if (editing) {
    return (
      <div className="rounded-md border border-border bg-muted/30 px-3 py-2">
        {/* biome-ignore lint/a11y/useFocusableInteractive: contentEditable is natively focusable. */}
        {/* biome-ignore lint/a11y/useSemanticElements: contentEditable needed for multi-line raw TeX input. */}
        <div
          ref={editorRef}
          contentEditable
          suppressContentEditableWarning
          role="textbox"
          aria-label="LaTeX formula"
          aria-multiline="true"
          className="min-h-[3em] w-full whitespace-pre-wrap font-mono text-sm outline-none"
          // biome-ignore lint/security/noDangerouslySetInnerHtml: tex is from trusted store state, no HTML injection risk (escaped before insert).
          dangerouslySetInnerHTML={{ __html: escapeHtml(tex) }}
          onBlur={commitAndPreview}
          onKeyDown={(e) => {
            // Shift+Enter → commit (single Enter is allowed for multiline TeX).
            if (e.key === "Enter" && e.shiftKey) {
              e.preventDefault();
              commitAndPreview();
            }
            // Escape → commit without change.
            if (e.key === "Escape") {
              e.preventDefault();
              commitAndPreview();
            }
          }}
        />
        <p className="mt-1 text-caption text-muted-foreground">
          Shift+Enter or blur to render
        </p>
      </div>
    );
  }

  // Preview mode — KaTeX HTML is trusted (generated by our facade from TeX).
  // Use <button> to satisfy a11y semantic element rules.
  return (
    <button
      type="button"
      aria-label="Math block. Click to edit."
      className="w-full cursor-pointer rounded-md border border-transparent px-2 py-1 text-left hover:border-border hover:bg-muted/20"
      onClick={() => setEditing(true)}
      // biome-ignore lint/security/noDangerouslySetInnerHtml: KaTeX output is generated by renderTexToHtml facade — trusted HTML.
      dangerouslySetInnerHTML={{
        __html: tex
          ? renderTexToHtml(tex, { displayMode: true })
          : `<span class="text-muted-foreground text-sm italic">Empty formula. Click to edit.</span>`,
      }}
    />
  );
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
