import {
  AlertTriangle,
  AlignLeft,
  Anchor,
  ArrowDownToLine,
  BadgeCheck,
  BarChart3,
  Bell,
  BellRing,
  BookOpen,
  BookText,
  Bot,
  Boxes,
  CalendarDays,
  ChevronDown,
  ChevronsRight,
  CircleDot,
  Code2,
  Columns3,
  FileImage,
  Flag,
  Footprints,
  FormInput,
  GalleryHorizontalEnd,
  GalleryVerticalEnd,
  Gauge,
  GaugeCircle,
  Gavel,
  GitBranch,
  Grid3x3,
  Hash,
  Heading1,
  Headphones,
  HelpCircle,
  Image as ImageIcon,
  Inbox,
  Info,
  Layers,
  LayoutGrid,
  LayoutPanelTop,
  LineChart,
  Link as LinkIcon,
  List,
  ListChecks,
  ListOrdered,
  type LucideIcon,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquareDashed,
  Minus,
  MoreHorizontal,
  MousePointer,
  Navigation,
  Palette,
  PanelBottom,
  PanelLeft,
  PanelTop,
  PercentSquare,
  Pilcrow,
  Plus,
  Quote,
  Rows3,
  Rss,
  Search,
  Settings2,
  Sigma,
  Signal,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Square,
  SquareDashed,
  Star,
  Table as TableIcon,
  Tag,
  Target,
  TextCursorInput,
  ToggleLeft,
  Type,
  Upload,
  UserSquare,
  Users,
  Video,
  Webhook,
} from "lucide-react";
import type { BlockKind } from "@/builder/types/entity";

export const BLOCK_ICONS: Record<BlockKind, LucideIcon> = {
  // docs
  heading: Heading1,
  paragraph: Pilcrow,
  blockquote: Quote,
  callout: Info,
  canvas: LayoutGrid,
  "code-block": Code2,
  "bullet-list": List,
  "numbered-list": ListOrdered,
  checklist: ListChecks,
  table: TableIcon,
  rule: Minus,
  figure: FileImage,
  "link-card": LinkIcon,
  definition: BookText,
  decision: Gavel,
  persona: UserSquare,
  "user-story": Users,
  risk: AlertTriangle,
  metric: GaugeCircle,
  milestone: Flag,
  "release-note": Tag,
  "color-swatch": Palette,
  "journey-step": Footprints,
  "api-endpoint": Webhook,
  "math-block": Sigma,
  // app
  "page-header": LayoutPanelTop,
  sidebar: PanelLeft,
  footer: PanelBottom,
  tabs: Layers,
  modal: SquareDashed,
  divider: Minus,
  nav: Menu,
  hero: Sparkles,
  "cta-section": Megaphone,
  "card-grid": Grid3x3,
  text: Type,
  list: List,
  image: ImageIcon,
  stat: Target,
  avatar: UserSquare,
  badge: Tag,
  form: FormInput,
  button: MousePointer,
  checkbox: Square,
  datepicker: CalendarDays,
  "file-upload": Upload,
  input: TextCursorInput,
  "radio-group": CircleDot,
  rating: Star,
  "search-input": Search,
  "segmented-control": Rows3,
  select: ChevronDown,
  slider: SlidersHorizontal,
  stepper: Hash,
  switch: ToggleLeft,
  textarea: AlignLeft,
  banner: Bell,
  "empty-state": Inbox,
  "status-bar": Signal,
  "bottom-nav": Navigation,
  "list-row": Rows3,
  fab: Plus,
  sheet: PanelTop,
  // Data group (PR-3)
  chart: LineChart,
  "kpi-card": Gauge,
  "progress-bar": PercentSquare,
  timeline: GitBranch,
  calendar: CalendarDays,
  // Media group (PR-4) — app context
  video: Video,
  audio: Headphones,
  // Communication group (PR-5)
  "ai-chat": Bot,
  "message-bubble": MessageSquare,
  // Navigation group (PR-6)
  breadcrumb: ChevronsRight,
  pagination: GalleryHorizontalEnd,
  // MoreHorizontal avoids collision with Menu (already used by nav)
  "dropdown-menu": MoreHorizontal,
  // Feedback group (PR-6)
  // BellRing avoids collision with Bell (already used by banner)
  toast: BellRing,
  tooltip: HelpCircle,
  // MessageSquareDashed avoids collision with MessageSquare (message-bubble)
  popover: MessageSquareDashed,
  // agent
  "agent-step": CircleDot,
  // shared structure
  layout: LayoutGrid,
};

export function iconForBlock(kind: BlockKind): LucideIcon {
  return BLOCK_ICONS[kind] ?? CircleDot;
}

export const GROUP_ICONS: Record<string, LucideIcon> = {
  Prose: BookOpen,
  Lists: List,
  Structure: Columns3,
  Media: ImageIcon,
  Reference: BookText,
  Spec: Settings2,
  Layout: LayoutGrid,
  Navigation: Navigation,
  Content: GalleryVerticalEnd,
  Input: FormInput,
  Feedback: Bell,
  Mobile: Smartphone,
  Agent: Sparkles,
  Data: BarChart3,
  Communication: MessageCircle,
};

export function iconForGroup(group: string): LucideIcon {
  return GROUP_ICONS[group] ?? Boxes;
}

// Re-exported for convenience.
export { Anchor, ArrowDownToLine, BadgeCheck, Hash, Rss };
