import {
  AlertTriangle,
  Anchor,
  ArrowDownToLine,
  BadgeCheck,
  Bell,
  BookOpen,
  BookText,
  Boxes,
  CircleDot,
  Code2,
  Columns3,
  FileImage,
  Flag,
  Footprints,
  FormInput,
  GalleryVerticalEnd,
  GaugeCircle,
  Gavel,
  Grid3x3,
  Hash,
  Heading1,
  Image as ImageIcon,
  Inbox,
  Info,
  Layers,
  LayoutGrid,
  LayoutPanelTop,
  Link as LinkIcon,
  List,
  ListChecks,
  ListOrdered,
  type LucideIcon,
  Megaphone,
  Menu,
  Minus,
  MousePointer,
  Navigation,
  Palette,
  PanelBottom,
  PanelLeft,
  PanelTop,
  Pilcrow,
  Plus,
  Quote,
  Rows3,
  Rss,
  Settings2,
  Sigma,
  Signal,
  Smartphone,
  Sparkles,
  SquareDashed,
  Table as TableIcon,
  Tag,
  Target,
  TextCursorInput,
  Type,
  UserSquare,
  Users,
  Webhook,
} from "lucide-react";
import type { BlockKind } from "@/builder/types/entity";

export const BLOCK_ICONS: Record<BlockKind, LucideIcon> = {
  // docs
  heading: Heading1,
  paragraph: Pilcrow,
  blockquote: Quote,
  callout: Info,
  canvas: LayoutGrid,
  "code-block": Code2,
  "bullet-list": List,
  "numbered-list": ListOrdered,
  checklist: ListChecks,
  table: TableIcon,
  rule: Minus,
  figure: FileImage,
  "link-card": LinkIcon,
  definition: BookText,
  decision: Gavel,
  persona: UserSquare,
  "user-story": Users,
  risk: AlertTriangle,
  metric: GaugeCircle,
  milestone: Flag,
  "release-note": Tag,
  "color-swatch": Palette,
  "journey-step": Footprints,
  "api-endpoint": Webhook,
  "math-block": Sigma,
  // app
  "page-header": LayoutPanelTop,
  sidebar: PanelLeft,
  footer: PanelBottom,
  tabs: Layers,
  modal: SquareDashed,
  divider: Minus,
  nav: Menu,
  hero: Sparkles,
  "cta-section": Megaphone,
  "card-grid": Grid3x3,
  text: Type,
  list: List,
  image: ImageIcon,
  stat: Target,
  avatar: UserSquare,
  badge: Tag,
  form: FormInput,
  button: MousePointer,
  input: TextCursorInput,
  banner: Bell,
  "empty-state": Inbox,
  "status-bar": Signal,
  "bottom-nav": Navigation,
  "list-row": Rows3,
  fab: Plus,
  sheet: PanelTop,
  // agent
  "agent-step": CircleDot,
  // shared structure
  layout: LayoutGrid,
};

export function iconForBlock(kind: BlockKind): LucideIcon {
  return BLOCK_ICONS[kind] ?? CircleDot;
}

export const GROUP_ICONS: Record<string, LucideIcon> = {
  Prose: BookOpen,
  Lists: List,
  Structure: Columns3,
  Media: ImageIcon,
  Reference: BookText,
  Spec: Settings2,
  Layout: LayoutGrid,
  Navigation: Navigation,
  Content: GalleryVerticalEnd,
  Input: FormInput,
  Feedback: Bell,
  Mobile: Smartphone,
  Agent: Sparkles,
};

export function iconForGroup(group: string): LucideIcon {
  return GROUP_ICONS[group] ?? Boxes;
}

// Re-exported for convenience.
export { Anchor, ArrowDownToLine, BadgeCheck, Hash, Rss };
